export interface IUelSetting {
  whitelist: string[];
  blacklist: string[];
  words_to_strip: string[];
  grades_to_strip: string[];
  punctuation_to_strip_regex: string;
  punctuation_pattern_regex: string;
  grade_punctuation_pattern_regex: string;
  emoji_regex: string;
}

export interface ICardSetUelSetting {
  whitelist: string[];
  blacklist: string[];
  words_to_strip: string[];
  grades_to_strip: string[];
}

export const EMPTY_UEL_SETTINGS: IUelSetting = {
  whitelist: [],
  blacklist: [],
  words_to_strip: [],
  grades_to_strip: [],
  punctuation_to_strip_regex: "[\\/\\-\\&\\\\]+|\\.{2,}",
  punctuation_pattern_regex: '[\\.\\!\\"\\*\\,\\(\\)\\d\\+\\\\]*',
  grade_punctuation_pattern_regex: '[\\"\\*\\,\\.\\!\\(\\)\\+]*',
  emoji_regex:
    "(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|\ud83c[\ude32-\ude3a]|\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])",
};

export const DEFAULT_UEL_SETTINGS: IUelSetting = {
  whitelist: [
    "national treasures",
    "pro set",
    "case hit",
    "mega box",
    "opening day",
    "national landmark",
    "national landmarks",
    "topps complete set",
    "fast break",
    "arriving now",
    "Question of Sport",
    "box set",
    "pack fresh",
    "1st",
    "Set Break",
    "giants of sport",
    "UFC Museum Collection",
    "Museum Collection UFC",
    "gallery of 1935",
    "gallery of 35",
    "gallery of '35",
  ],
  blacklist: ["?", "a&g", "k-mart"],
  words_to_strip: [
    "rcr",
    "lot",
    "not",
    "non",
    "bccg",
    "set",
    "box",
    "sealed",
    "pack",
    "repack",
    "re-pack",
    "x2",
    "case",
    "vip",
    "friday",
    "relic",
    "cyber",
    "emergent",
    "lottery",
    "crusades",
    "swatch",
    "archive",
    "cognac",
    "fire",
    "3d",
    "advent",
    "mini",
    "opening",
    "tbt",
    "big",
    "signed",
    "factory",
    "legends",
    "socks",
    "ginter",
    "lineage",
    "wrapper",
    "kmart",
    "derby",
    "demand",
    "now",
    "gypsy",
    "throwback",
    "living",
    "game",
    "hightek",
    "tek",
    "museum",
    "salute",
    "limited",
    "tribute",
    "scouts",
    "inauguration",
    "AFL",
    "printing",
    "plate",
    "archives",
    "perspectives",
    "toolsey",
    "farmhands",
    "stat",
    "franchise",
    "transcendent",
    "dynamic",
    "Complete",
    "History",
    "Decade",
    "Gear",
    "Fathers",
    "National",
    "Legacy",
    "Hype",
    "Illusions",
    "Bowl",
    "AKA",
    "Gridiron",
    "Razzle",
    "Prototype",
    "Prototypes",
    "Trifecta",
    "Pairs",
    "Intros",
    "Helmets",
    "Marshalls",
    "ref",
    "international",
    "intl",
    "vintage",
    "homerun",
    "decade",
    "challenge",
    "challenger",
    "vintage",
    "error",
    "please",
    "read",
    "breakdown",
    "break",
    "armour",
    "speckel",
    "speckle",
    "reprint",
    "refactor",
    "gma",
    "silver base",
    "base silver",
    "PD",
    "ST",
    "OF",
    "MK",
    "MC",
    "damaged",
    "digital",
    "PGI",
    "RP",
    "mba",
    "IP",
    "ksa",
    "reprints",
    "oversize",
    "oversized",
    "minis",
    "packs",
    "regrade",
    "hga",
    "looks",
    "should",
    "scratch",
    "scratches",
    "scratched",
    "ding",
    "dings",
    "bent",
    "crease",
    "creased",
    "scuff",
    "scuffed",
    "description",
    "honors",
    "csg",
  ],
  grades_to_strip: [],
  punctuation_to_strip_regex: "[\\/\\-\\&\\\\]+|\\.{2,}",
  punctuation_pattern_regex: '[\\.\\!\\"\\*\\,\\(\\)\\d\\+\\\\]*',
  grade_punctuation_pattern_regex: '[\\"\\*\\,\\.\\!\\(\\)\\+]*',
  emoji_regex:
    "(?:[\u2700-\u27bf]|(?:\ud83c[\udde6-\uddff]){2}|[\ud800-\udbff][\udc00-\udfff]|[\u0023-\u0039]\ufe0f?\u20e3|\u3299|\u3297|\u303d|\u3030|\u24c2|\ud83c[\udd70-\udd71]|\ud83c[\udd7e-\udd7f]|\ud83c\udd8e|\ud83c[\udd91-\udd9a]|\ud83c[\udde6-\uddff]|\ud83c[\ude01-\ude02]|\ud83c\ude1a|\ud83c\ude2f|\ud83c[\ude32-\ude3a]|\ud83c[\ude50-\ude51]|\u203c|\u2049|[\u25aa-\u25ab]|\u25b6|\u25c0|[\u25fb-\u25fe]|\u00a9|\u00ae|\u2122|\u2139|\ud83c\udc04|[\u2600-\u26FF]|\u2b05|\u2b06|\u2b07|\u2b1b|\u2b1c|\u2b50|\u2b55|\u231a|\u231b|\u2328|\u23cf|[\u23e9-\u23f3]|[\u23f8-\u23fa]|\ud83c\udccf|\u2934|\u2935|[\u2190-\u21ff])",
};
